v2.10.0 - upgrade to React 17
zooniverse/modal-form pull request #50
Opened 2022-06-17 21:41 UTC by shaunanoordin

## PR Overview

This PR upgrades the peer dependencies to React 17, and bumps the package to version 2.10.0

This repo may be deprecated, but it's still a dependency on Panoptes-Front-End. Its usage of React 16 is causing serious issues with the build process on Node 16.15. See zooniverse/Panoptes-Front-End#6155

### Status

- WIP. Changes should work in theory, but I'm testing a local PFE build with this.
- I'm trying to see how far I can update the other dependencies as well, for security's sake.

2022-06-17 21:44 UTC, shaunanoordin commented
Oh thank gods the other dependencies could be updated with no issues. `npm audit fix` is now clear.

2022-06-17 23:46 UTC, eatyourgreens requested changes
Peer dependencies should be React greater than 16.2.

2022-06-17 23:46 UTC, eatyourgreens commented on package.json
> +    "react-dom": "^17.x"
The peer dependencies should include React 16 and React 17.  See Markdownz for an example.

2022-07-25 11:15 UTC, shaunanoordin commented
I'm closing PR this since it's no longer too urgent - we have a workaround for PFE PR 6155, which is to use `--legacy-peer-deps`.

2022-07-25 11:15 UTC, closed without merging